{% set name = "pycallgraph2" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycallgraph2-{{ version }}.tar.gz
  sha256: f5d02c1ea446cd7051ad886fc61c6698c1d1f6b759ac5e32ddec5fab153b73c8

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
    # To address "error in pycallgraph2 setup command: use_2to3 is invalid"
    - setuptools <58
  run:
    - python >={{ python_min }}

test:
  imports:
    - pycallgraph2
    - pycallgraph2.output
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/daneads/pycallgraph2
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Python Call Graph is a Python module that creates call graph visualizations for Python applications.
  description: |
    This is a fork of the original pycallgraph since it became unmaintained.
    The project lives on GitHub, where you can report issues, contribute to the project by forking the project then creating a pull request, or just browse the source code.
    The fork needs documentation. Feel free to contribute :)
  dev_url: https://github.com/daneads/pycallgraph2

extra:
  recipe-maintainers:
    - thewchan
